### ISSUE TITLE
Suggestions on the color of template strings '&{}' in JS / TS

### ISSUE THREAD

**Issue by Future23365** [uloco/theme-bluloco-dark#13]
你好，我非常喜欢你的主题。但是在JS/TS中有个小问题你可否改进下呢：
使用模板字符串语法时，如果在console.log中使用，‘${}’可以显示出颜色
但是，当我使用模板字符串给变量赋值时，‘${}'未变色。
这个问题能否修改下呢~
主题真的非常好看~
——————————
Hello, I like your theme very much. But there is a small problem in JS / ts. can you improve it:
When using template string syntax, if used in console.log, '${}' can display color
However, when I assign a value to a variable using a template string, '${}' does not change color.
Can this question be revised~
This theme is really beautiful~

![image](https://user-images.githubusercontent.com/40729618/136727239-7842f3a1-3d38-41b1-bcf4-c7b37df8e566.png)

**Comment by uloco** [comment]
Hi, thanks for your feedback. I think this issue is not related to the theme but you are using the extension "bracket pair colorizer", the settings configuration `"editor.bracketPairColorization.enabled"` or something similar. Try disabling it and the problem should get resolved.

For me it looks like this, since I do not have this enabled:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/8818340/136744179-2b94727d-b3b1-4a6d-a57d-4220953a132c.png">

I have just found out, that I could also theme this colors used by the bracketPairColorization, but I think it would confuse a lot of people.

**Comment by uloco** [comment]
If you really need to use the bracket pair colorization you can try adding this in your `settings.json`
```
  "workbench.colorCustomizations": {
    "[Bluloco Dark]": {
      "editorBracketHighlight.foreground1": "#92f535",
      "editorBracketHighlight.foreground2": "#28e4eb",
      "editorBracketHighlight.foreground3": "#ffa023",
      "editorBracketHighlight.foreground4": "#00ff95",
      "editorBracketHighlight.foreground5": "#ff78ff",
      "editorBracketHighlight.foreground6": "#ffffff",
      "editorBracketHighlight.unexpectedBracket.foreground": "#ff0000"
    }
  },
```

Then your brackets will be colored like this:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/8818340/136748492-18d424c9-d74a-411f-9a05-66df7e3c3eea.png">

**Comment by Future23365** [comment]
Thank you very much. 😄
