### ISSUE TITLE
Highlighted text is barely visible

### ISSUE THREAD

**Issue by Codermar** [uloco/theme-bluloco-dark#9]
I started to use this theme and I like it but there's one problem. The highlighted text either when selecting a word or the search highlight does not have enough contrast and makes it really hard to see. @

**Comment by uloco** [comment]
Thanks for your feedback! I am quite happy with the highlighting to be honest, maybe you have an idea to make it better? But of course this is a very opinionated topic and I am not sure wether I want to get persuaded at all 😄 Could also be your monitor panel/settings. I am testing it mostly on sRGB IPS panels or MacbookPro. The hard part about high contrast highlighting is to keep the text still readable in many different colors because the foreground changes. Also the colors need to have transparency to prevent overshadowing some error markers for example.

Of course you can always change just a few colors as you like in your user settings file like so:

```
  "workbench.colorCustomizations": {
    "[Bluloco Dark]": {
      "editor.findMatchHighlightBackground": "#00ff006b",
      "editor.findMatchBackground": "#00ff006b",
      "editor.wordHighlightBackground": "#033083b0",
      "editor.wordHighlightStrongBackground": "#780f73ae",
      "editor.selectionHighlightBackground": "#03030355",
      "editor.selectionBackground": "#03030355"
    }
  },
```
This is just a quick example, not sure if the colors suit you, but you can adjust accordingly 😉
Would be interested in the outcome though.
